UserGallery/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.u_gallery,name='u_gallery'),
    path('create_playlist/',views.create_playlist.as_view(),name="create_playlist"),
    path('details/<int:pk>',views.detail_view.as_view(),name="detail"),
    path('update/<int:pk>',views.update_playlist.as_view(),name="update"),
    path('delete/<int:pk>',views.delete_playlist.as_view(),name="delete"),
    
    path('addvideo/<int:pk>',views.add_video,name="add_video"),
    path('deletevideo/<int:pk>',views.delete_video.as_view(),name="delete_video"),
    path('addvideo/video/search',views.video_search,name="video_search"),

]

VideoGallery/urls.py
from django.contrib import admin
from django.urls import path,include
from VideoGallery import settings
from .import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('user_gallery/',include('UserGallery.urls')),
    path('accounts/', include('allauth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

UserGallery/models.py
from django.db import models
from  django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    demo = models.CharField(max_length=100)

    def __str__(self):
        return self.email



class PlayList(models.Model):
    title = models.CharField(max_length=250)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def video_count(self):
        video = Video.objects.filter(playlist=self,playlist__user=self.user).count()
        return video


class Video(models.Model):
    title = models.CharField(max_length=250)
    url = models.URLField()
    youtube_id = models.CharField(max_length=100)
    playlist = models.ForeignKey(PlayList,on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.playlist.title

UserGallery/forms.py
from allauth.account.forms import SignupForm
from django import forms
from .models import Video

class SimpleSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')
    demo = forms.CharField(max_length=100, label='test')

    def save(self, request):
        user = super(SimpleSignupForm, self).save(request)
        user.demo = self.cleaned_data['demo']
        user.save()
        return user

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

class AddvideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']


class SearchvideoForm(forms.Form):
    search_term = forms.CharField(max_length=255, label="Search for videos")

UserGallery/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.http import Http404,HttpResponse,JsonResponse
from .models import PlayList,Video
from .forms import AddvideoForm,SearchvideoForm
from django.contrib import messages
import urllib
import requests
from django.conf import settings

YOUTUBE_API_KEY = settings.YOUTUBE_API_KEY
# https://youtube.googleapis.com/youtube/v3/search?part=snippet&relatedToVideoId=3QNBVG2yqKA&type=video&key=[YOUR_API_KEY]
# https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id=3QNBVG2yqKA&key=[YOUR_API_KEY]
# https://youtube.googleapis.com/youtube/v3/search?part=snippet&q=eggs&key=[YOUR_API_KEY]

# Create your views here.

def video_search(request):
    search_form = SearchvideoForm(request.GET)
    if search_form.is_valid():
        search = search_form.cleaned_data['search_term']
        encoded_search_term = urllib.parse.quote(search)
        response = requests.get(f'https://youtube.googleapis.com/youtube/v3/search?part=snippet&q={encoded_search_term}&key={YOUTUBE_API_KEY}')

        return JsonResponse(response.json())

    return JsonResponse({'Sorry':'Not Working'})


@login_required
def u_gallery(request):
    playlists = PlayList.objects.filter(user=request.user)
 


    context = {

        'playlists': playlists,

    }


    return render(request,'gallery/user_gallery.html',context)


@method_decorator(login_required, name='dispatch')
class create_playlist(generic.CreateView):
    model = PlayList
    fields = ['title']
    template_name  = 'gallery/create_playlist.html'
    success_url = reverse_lazy('u_gallery')

    def form_valid(self, form):
        form.instance.user=self.request.user
        super(create_playlist,self).form_valid(form)
        return redirect('u_gallery')

@method_decorator(login_required,name='dispatch')
class detail_view(generic.DetailView):
        model = PlayList
        template_name = 'gallery/detail_playlist.html'
        def get_context_data(self, **kwargs):

            context = super().get_context_data(**kwargs)

            context['videos'] = Video.objects.filter(playlist__user=self.request.user,playlist__id=self.kwargs.get('pk'))
            return context


@method_decorator(login_required, name='dispatch')
class update_playlist(generic.UpdateView):
    model = PlayList
    fields = ['title']
    template_name  = 'gallery/update_playlist.html'
    success_url = reverse_lazy('u_gallery')


@method_decorator(login_required, name='dispatch')
class delete_playlist(generic.DeleteView):
    model = PlayList
    template_name  = 'gallery/delete_playlist.html'
    success_url = reverse_lazy('u_gallery')



@login_required
def add_video(request,pk):

    playlist = PlayList.objects.get(pk=pk)

    if not playlist.user == request.user:
        return HttpResponse("Playlist doesn't belongs to you")

    else:

        form = AddvideoForm()
        search_form = SearchvideoForm()

        if request.method == 'POST':

            video_form = AddvideoForm(request.POST)

            if video_form.is_valid():
                video = Video()
                video.playlist = playlist
                video.url = video_form.cleaned_data['url']
                parsed_url = urllib.parse.urlparse(video.url)
                video_id = urllib.parse.parse_qs(parsed_url.query).get('v')

                if video_id:

                    video.youtube_id = video_id[0]
                    if Video.objects.filter(youtube_id=video.youtube_id,playlist=video.playlist.id).exists():
                        messages.error(request,'Video already exists in your playlist!')

                    else:

                        response = requests.get(f'https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id={video_id[0]}&key={YOUTUBE_API_KEY}')
                        json = response.json()
                        title = json['items'][0]['snippet']['title']
                        video.title = title
                        video.save()

                else:
                    
                    messages.error(request,"Not a youtube url")
        context = {'form' : form,'search_form': search_form,'playlist' : playlist}
        return render(request,'gallery/add_video.html',context)


@method_decorator(login_required, name='dispatch')
class delete_video(generic.DeleteView):
    model = Video
    template_name  = 'gallery/delete_video.html'
    success_url = reverse_lazy('u_gallery')

VideoGallery/views.py
from django.shortcuts import render
from UserGallery.models import PlayList





def home(request):
    if request.user.is_authenticated:


        playlist = PlayList.objects.filter(user=request.user)
        context = {
            'playlist' : playlist
        }
        return render(request,'home.html',context)
    return render(request,'home.html')
    

templates/gallery/add_video.html
{% extends 'account/base.html' %}
{% load crispy_forms_filters %}

{% block content %}

<div class="container">
    
    <h3>Add Video to {{playlist.title}}</h3>
    <form action="" method="post" id="submit_search">
        {% csrf_token %}
        <div  class="mb-2">
            {{ form|crispy }}
        </div>
        
        <button type="submit" class="btn-primary form-control" >Add Video</button>

    </form>
<br>
<br>
    <h1>OR</h1>

    <form>
        <div  class="mb-2">
        {{search_form|crispy}}
        </div>
        <!-- <button type="submit" class="btn-danger form-control">search Video</button> -->
    </form>

    <div id="search_result">

    </div>

    <script>
        var delayTimer;
        $('#id_search_term').keyup(function(){
            clearTimeout(delayTimer);
            $('#search_result').text('Loading.....');
            delayTimer = setTimeout(function(){
                var text = $('#id_search_term').val();
                $.ajax({
                    url : 'video/search',
                    data : {
                        'search_term' : text
                    },
                    dataType : 'json',
                    success : function(data){

                        var result = "";

                        $('#search_result').text('');
                        result += '<div class="row">';
                        data['items'].forEach(function(video){
                            result += '<div class="col-md-4 mt-2"><div class="card mb-3 shadow-sm">';
                            result += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' +video['id']['videoId']+ '" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
                            result += '<div class="card-body"><p class="card-text">' + video['snippet']['title'] + '</p>';
                            result += '<a href="#" class="btn btn-primary" onclick="addVideo(\''+ video['id']['videoId'] +'\')">Add</a></div></div></div>'
                            
                        });
                        result += '</div>';

                        $('#search_result').append(result);
                    },
                });
 
            }, 1000);
        });

        function addVideo(video_id){
            $('#id_url').val('https://www.youtube.com/watch?v='+ video_id);
            $('#submit_search').submit()
        }
    </script>
</div>

{% endblock %}

templates/gallery/create_playlist.html
{% extends 'account/base.html' %}
{% load crispy_forms_filters %}
{% block content %}

<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <div  class="mb-2">
            {{ form|crispy }}
        </div>
        
        <input type="submit" value="create playlist" class="btn-primary form-control">
    </form>
</div>

{% endblock %}

templates/gallery/delete_playlist.html
{% extends 'account/base.html' %}
{% load crispy_forms_filters %}
{% block content %}

<div class="container">
    <h3>Do you want to delete your playlist:</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div class="my-2">
            {{form.as_p}}
            {{playlist.title}}
        </div>
        
        <button type="submit" class="btn-danger form-control">delete</button>
    </form>
    <div class="mt-5">
    <span>Recheck your playlist : <a href="{% url 'detail' playlist.id %}" class="text-decoration-none">{{playlist.title}}</a></span>
    </div>
</div>

{% endblock %}

templates/gallery/delete_video.html
{% extends 'account/base.html' %} 
{% load crispy_forms_filters %} 
{% block content %}

<div class="container">
  <h3>Do you want to delete your playlist:</h3>
  <form action="" method="post">
    {% csrf_token %}
    <div class="my-2">{{form.as_p}} {{video.title}}</div>

    <button type="submit" class="btn-danger form-control">delete</button>
  </form>

  <div class="row">
    <div class="col-md-4 mt-2">
      <div class="card mb-3 shadow-sm">
        <iframe
          width="100%"
          height="225"
          src="https://www.youtube.com/embed/{{video.youtube_id}}"
          title="YouTube video player"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>
        <div class="card-body">
          <p class="card-text">{{video.title}}</p>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/gallery/detail_playlist.html
{% extends 'account/base.html' %}
{% load crispy_forms_filters %}
{% block content %}

<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <div  class="mb-2 text-center">
            <b>Playlist</b> : {{ playlist.title }}
          <br>
            <br>
            {% if videos %}
            <span><a href="{% url 'add_video' playlist.id %}" class="btn btn-danger">Add new video to playlist</a></span>
            {% else %}
            <b>You don't have any video in your playlist </b><br><br>
            <span><a href="{% url 'add_video' playlist.id %}" class="btn btn-danger">Add new video to playlist</a></span>
            {% endif %}
        </div>

 <br><br>

        <div class="row">

          {% for video in videos %}
            <div class="col-md-4 mt-2">
              <div class="card mb-3 shadow-sm">
                <iframe
                  width="100%"
                  height="225"
                  src="https://www.youtube.com/embed/{{video.youtube_id}}"
                  title="YouTube video player"
                  frameborder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowfullscreen
                ></iframe>
                <div class="card-body">
                  <p class="card-text">{{video.title}}</p>
                  <span><a href="{% url 'delete_video' video.id %}" class="btn btn-danger">delete video</a></span>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>



    </form>
</div>

{% endblock %}

templates/gallery/update_playlist.html
{% extends 'account/base.html' %}
{% load crispy_forms_filters %}
{% block content %}

<div class="container">
    <h3>Edit your playlist:</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div  class="mb-2">
            {{ form|crispy }}
        </div>
        
        <button type="submit" class="btn-primary form-control">Save</button>
    </form>
</div>

{% endblock %}

templates/gallery/user_gallery.html
{% extends 'account/base.html' %}

{% block content %}
<div class="text-center">
    <h3>Welcome to {{user.username}}'s gallery</h3>
    {% if playlists %}

    <a href="{% url 'create_playlist' %}" class="btn btn-primary">Create Playlist</a>

    {% else %}

    <b>You don't have any playlist</b>
    <br><br>
    <a href="{% url 'create_playlist' %}" class="btn btn-primary">Create Playlist</a>


    {% endif %}
</div>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col">
            <table class="table table-hover text-center">
                <thead>
                  <tr>
                    <th scope="col">playlist</th>
                    <th scope="col">playlist name</th>
                    <th scope="col">number of Video's</th>
                    <th scope="col">check playlist</th>
                    <th scope="col">delete playlist</th>
                  </tr>
                </thead>
                <tbody>

                    {% for playlist in playlists %}
                  <tr>
                    <th scope="row">{{playlist.id}}</th>
                    <td>{{playlist.title}}<span class="ml-2"><a href="{% url 'update' playlist.id %}"><i class="fas fa-edit"></i></a></span></td>
                    <td>{{playlist.video_count}}<span class="ml-2"><a href="{% url 'add_video' playlist.id %}"><i class="fas fa-plus"></i></a></span></td>
                    <td>
                      
                      <a href="{% url 'detail' playlist.id %}" class="btn btn-success">check detail</a>
                    
                    </td>
                    <td>
                      
                      <a href="{% url 'delete' playlist.id %}" class="btn btn-danger">delete playlist</a>
                    
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
</div>

{% endblock %}

templates/home.html
{% extends 'account/base.html' %}



{% block content%}


<div class="container text-center bgi">
    {% if not user.is_authenticated %}

        <h2>Welcome to Video Playlist website</h2>
        <h4>Create your own video playlist</h4>
        <a href="{% url 'account_login' %}" class="btn btn-outline-dark">Get Started</a>

    {% else %}

    <h2>Welcome to {{user.username}}'s Video Gallery</h2>
    <h4>Click here to check dashboard</h4>
    <a href="{% url 'u_gallery' %}" class="btn btn-outline-dark">Get Started</a>

    {% endif %}

</div>

{% endblock %}